### ISSUE TITLE
Paper 1.15.1 Exception

### ISSUE THREAD

**Issue by ShayBox** [DarkZek/AutoReload#1]
```
[10:39:07] [Craft Scheduler Thread - 15/WARN]: [AutoReload] Plugin AutoReload v1.02 generated an exception while executing task 22
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:715) ~[patched_1.15.1.jar:git-Paper-31]
	at com.darkzek.autoreload.AutoReload.checkIfModified(AutoReload.java:81) ~[?:?]
	at com.darkzek.autoreload.AutoReload$1.run(AutoReload.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-31]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by DarkZek** [comment]
Thank you for reporting this issue!
I've just posted the updated jar to spigot that fixes this issue
